[package]
name = "choccy_tui"
version = "0.1.0"
edition = "2021"

[dependencies]
crossterm = "0.27.0"
ratatui = "0.26.3"
choccy_chip = {version = "0.1.0", path = "../choccy_chip"}
color-eyre = "0.6.3"
